### ISSUE TITLE
Création du type de contenu actualité

### ISSUE THREAD

**Issue by sographik** [jabberwooki/amp#1]
- Image (obligatoire)
- Partage réseaux sociaux
- Date de publication (automatique)
- Titre (obligatoire)
- Résumé (obligatoire), limité en nombre de caractère
- Bundles paragraphs

**Comment by jabberwooki** [comment]
Type de contenu créé, y compris la limitation du nb de caractères du résumé.
Création de la vue Actualités avec les display bloc accueil, page et full node.
Création des crop types et des styles d'image pour les actus.
