### ISSUE TITLE
Sendinblue paramétrage module pour formulaire inscription newsletter

### ISSUE THREAD

**Issue by sographik** [jabberwooki/amp#23]

**Comment by jabberwooki** [comment]
Module paramétré, mais pas simple à faire.
Une clé d'API pour chaque instance (2 dev, 1 recette, 1 prod).
Les fichiers de conf (paramétrages sendinblue ET positionnement du bloc accueil) sont placés dans .gitignore. Tout doit être propre à chaque site, chacun doit construire sont bloc.
