### ISSUE TITLE
Copyright sur tous les champs images !

### ISSUE THREAD

**Issue by sographik** [jabberwooki/amp#9]

**Comment by jabberwooki** [comment]
Fonctionnalité mise en place à l'aide du module image_title_caption, créé par Sitepoint mais non encore publié. Donc copié dans modules/custom et adapté.
Références : 
[Article de Sitepoint](https://www.sitepoint.com/community/t/creating-custom-field-formatters-in-drupal-8/115179)
[module chez Github](https://github.com/sitepoint-editors/image_title_caption)
